server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/orm
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#    mapper:
#      mappers:
#        - tk.mybatis.mapper.common.Mapper
#        - tk.mybatis.mapper.common.Mapper2
#      notEmpty: true


#mybatis:
#  mapper-locations: classpath*:/mybatis/mapper/*.xml
#  type-aliases-package: com.duing.model



#    带xml配置文件类型
#  config-location: classpath:mybatis-config.xml
